# Copyright Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# NB: we're not providing `rfigui`.

{% set name = "aoflagger" %}
{% set version = "3.4.0" %}
{% set fileid_for_version = "96704214" %}
{% set sha256 = "9560b7381b68f37d842599f222a8aa2a5d3d3d501d1277471e1a0ba3d7b2aeba" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/aroffringa/aoflagger/-/package_files/{{ fileid_for_version }}/download
  fn: {{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake <4
    - ninja
    - python
  host:
    - casacore
    - cfitsio 4.6.2  # force migration pin for correct casacore
    - fftw
    - gsl
    - hdf5
    - libblas
    - libboost-devel 1.86  # force migration pin for correct casacore
    - libboost-python 1.86  # force migration pin for correct casacore
    - libcblas
    - liblapack
    - libpng
    - libxml2
    - lua
    - numpy 2  # force migration pin for correct casacore
    - python
  run:
    - {{ pin_compatible("numpy") }}
    - python

about:
  home: http://aoflagger.sourceforge.net/
  license: GPLv3
  summary: automatic flagging of interference in radio astronomical data sets
