# Copyright 2015-2021 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# We don't provide the rfigui right now. It needs Gtk-- > 3.0, so it wouldn't
# be a huge amount of work to make that work since we have the Gtk+ 3 stack.
# We'd need libsigc++, glibmm, and gtkmm.

{% set name = "aoflagger" %}
{% set version = "2.15.0" %}
{% set sha256 = "0d080471944fd968403b69946ccf5076d7cd9c11a4aa626bb10dc926bdd4828e" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/aroffringa/aoflagger/-/archive/v{{ version }}/aoflagger-v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - mac-cxx.patch
    - boost-python3.patch

build:
  number: 2
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    # This list based on DT_NEEDED libraries in the executable
    - boost {{ boost }}
    - boost-cpp {{ boost_cpp }}
    - casacore 3.3.*  # NB: casa-tools currently requires casacore 3.3 and we need to stay compatible
    - cfitsio {{ cfitsio }}
    - fftw {{ fftw }}
    - gsl {{ gsl }}
    - hdf5 {{ hdf5 }}
    - libblas {{ libblas }}
    - libcblas {{ libcblas }}
    - liblapack {{ liblapack }}
    - libpng {{ libpng }}
    - libxml2 {{ libxml2 }}
    - lua
    - numpy
    - python
  run:
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('numpy') }}
    - python

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://aoflagger.sourceforge.net/
  license: GPLv3
  summary: automatic flagging of interference in radio astronomical data sets
