# Copyright 2015-2022 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# We don't provide the rfigui right now. It needs Gtk-- > 3.0, so it wouldn't
# be a huge amount of work to make that work since we have the Gtk+ 3 stack.
# We'd need libsigc++, glibmm, and gtkmm.

{% set name = "aoflagger" %}
{% set version = "3.2.0" %}
{% set fileid_for_version = "38600488" %}
{% set sha256 = "c13542a99746e4541a54f3d05d7803934ea9580b9612242fa83df6f3a1883dec" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/aroffringa/aoflagger/-/package_files/{{ fileid_for_version }}/download
  fn: {{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  script_env:
    - NJOBS

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - python
  host:
    # This list based on DT_NEEDED libraries in the executable
    - boost {{ boost }}
    - boost-cpp {{ boost_cpp }}
    - casacore
    - cfitsio {{ cfitsio }}
    - fftw {{ fftw }}
    - gsl {{ gsl }}
    - hdf5 {{ hdf5 }}
    - libblas {{ libblas }}
    - libcblas {{ libcblas }}
    - liblapack {{ liblapack }}
    - libpng {{ libpng }}
    - libxml2 {{ libxml2 }}
    - lua
    - numpy
    - python
  run:
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('numpy') }}
    - python

about:
  home: http://aoflagger.sourceforge.net/
  license: GPLv3
  summary: automatic flagging of interference in radio astronomical data sets
