# Copyright 2015-2018 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# We don't provide the rfigui right now. It needs Gtk-- > 3.0, so it wouldn't
# be a huge amount of work to make that work since we have the Gtk+ 3 stack.
# We'd need libsigc++, glibmm, and gtkmm.

{% set name = "aoflagger" %}
{% set version = "2.10.0" %}
{% set sha256 = "3ec1188d37101acf2029575ebc09c50b19c158c88a12b55ac5d25a96bd8fc18d" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - mac-cxx.patch
    - boost-python3.patch  # [py3k]
    - mem-210-bugfix.patch

build:
  number: 2
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - boost 1.66.0
    - casacore 2.4.*
    - cfitsio 3.*
    - fftw 3.3.*
    - gsl 2.2.*
    - hdf5 1.10.1
    - libxml2 2.9.*
    - openblas 0.2.20|0.2.20.*
    - python
  run:
    - boost 1.66.0
    - casacore 2.4.*
    - cfitsio 3.*
    - fftw 3.3.*
    - gsl 2.2.*
    - hdf5 1.10.1
    - libxml2 2.9.*
    - openblas 0.2.20|0.2.20.*
    - python

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://aoflagger.sourceforge.net/
  license: GPLv3
  summary: automatic flagging of interference in radio astronomical data sets
