# Copyright 2015-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# A new tag must be pushed to GitHub for every update!

{% set name = "casa-python" %}
{% set version = "5.4.1" %}
{% set build = "2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/pkgw/casa.git
  git_rev: casa3k-{{ version }}_{{ build }}

build:
  number: {{ build }}
  skip: true  # [win]
  script_env:
    - NJOBS
  run_exports:
    - {{ pin_subpackage('casa-python', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - casa-tools 5.4.*
    - numpy
    - python
    - rpfits 2.*
    - wcslib
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - rpfits 2.*
    - {{ pin_compatible('wcslib') }}

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: Python interfaces to the CASA tools

test:
  imports:
    - casac

extra:
  recipe-maintainers:
    - pkgw
