# Copyright 2015-2021 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# A new tag must be pushed to GitHub for every update!

{% set name = "casa-python" %}
{% set version = "5.6.3" %}
{% set build = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/pkgw/casa.git
  git_rev: casa3k-{{ version }}_{{ build }}

build:
  number: {{ build }}
  skip: true  # [win]
  script_env:
    - NJOBS
  run_exports:
    - {{ pin_subpackage('casa-python', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    # These are deps that libtools.so ends up linking with directly --
    # casa-tools may drag in many of them, but we should explicitly
    # name them here to avoid binary compat issues.
    - casacore
    - casa-tools 5.6
    - dbus-cxx 0.9
    - ncurses {{ ncurses }}
    - numpy
    - python
    - qt4 4.8
    - readline {{ readline }}
    - xerces-c28

  run:
    - {{ pin_compatible('numpy') }}
    - python

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: Python interfaces to the CASA tools

test:
  imports:
    - casac

extra:
  recipe-maintainers:
    - pkgw
