# Copyright 2015-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `so-versioning.patch`.

package:
  name: casa-python
  version: "4.6.0"

source:
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_6/
  svn_rev: 36590
  svn_ignore_externals: yes
  patches:
    - so-versioning.patch
    - casadef.patch
    - ncursesw.patch

build:
  number: 6
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - casa-tools 4.6.*
    - cmake
    - libgfortran  # [linux]
    - ncurses 5.9
    - nomkl # speed by avoiding big download
    - python
    - rpfits 2.*
    - swig
    - wcslib 5.16
  run:
    - casa-tools 4.6.*
    - libgfortran  # [linux]
    - ncurses 5.9
    - python
    - rpfits 2.*
    - wcslib 5.16

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: Python interfaces to the CASA tools
