# Copyright 2015-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# A new tag must be pushed to GitHub for every update!

{% set name = "casa-python" %}
{% set version = "5.0.0" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/pkgw/casa.git
  git_rev: casa3k-{{ version }}_{{ build }}

build:
  number: {{ build }}
  detect_binary_files_with_prefix: true
  skip: true  # [win]
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - gcc  # [osx]
    - swig
    - toolchain
    - casa-tools 5.0.*
    - numpy 1.13.*
    - python
    - rpfits 2.*
    - wcslib 5.16
  run:
    - libgfortran  # [unix]
    - casa-tools 5.0.*
    - ncurses 5.9*
    - numpy 1.13.*
    - python
    - rpfits 2.*
    - wcslib 5.16

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: Python interfaces to the CASA tools

tests:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  imports:
    - casac

extra:
  recipe-maintainers:
    - pkgw
