# Copyright 2014-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: ninja
  version: "1.6.0"

source:
  fn: v1.6.0.tar.gz
  url: https://github.com/martine/ninja/archive/v1.6.0.tar.gz
  sha256: b43e88fb068fe4d92a3dfd9eb4d19755dae5c33415db2e9b7b61b4659009cde7

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
  run:

about:
  home: https://ninja-build.org/
  license: Apache 2.0
  summary: A small build system with a focus on speed.
