--- a/src/makefile
+++ b/src/makefile
@@ -20,11 +20,11 @@
 CXX = mpic++
 
 # Linker flags:
-LDFLAGS = -L -L/usr/lib -lm -lhdf5 -lgomp
+LDFLAGS = -L$PREFIX/lib -lm -lhdf5
   # -L is directory with libraries, there exists a file libm.sl etc.
 
 # Compiler flags
-CPPFLAGS = -I/usr/include/mpi -Wall -O0 -g -fopenmp
+CPPFLAGS = -Wall -O2 -g ${CXXFLAGS}
 #CPPFLAGS = -I/usr/include/mpi -Wall -O3 -march=native -mtune=native
   # -Wall all warnings on
   # -O3 Optimization level 3 ( -O0 needed for debugging purposes )
