# Copyright 2016-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Anaconda has moved on to Qt5, but CASA requires Qt4. We need to provide our
# own version since there are so many dependencies, and we also need to
# provide DBus support on OS X. This is not included in the stock version,
# likely because dbus-cxx is totally busted.

{% set name = "qt4" %}
{% set version= "4.8.7" %}
{% set sha256 = "e2882295097e47fe089f8ac741a95fef47e0a73a3f3cdf21b56990638f626ea0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: qt-everywhere-opensource-src-{{ version }}.tar.gz
  url: https://download.qt.io/archive/qt/4.8/{{ version }}/qt-everywhere-opensource-src-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Make Qt accept its open source license without user interaction
    - acceptance.patch
    # Make the paths in config.cpp longer so they work with conda-build 2.x
    - config.cpp.longpath.patch  # [unix]
    # Compile qmake with the system architecture. Taken from the MacPorts project:
    # https://trac.macports.org/browser/trunk/dports/aqua/qt4-mac/files/patch-configure.diff
    - qmake-arch.patch  # [osx]
    # Set the minimum deployment target to 10.9
    - osx_deployment_target_10.9_qmake.conf.patch  # [osx]
    # Enabling our test to set the rpath by making Qt aware
    # of how to do this on OSX
    - osx_rpath.qmake.conf.patch  # [osx]
    # fix use of deprecated OSX API. Taken from Homebrew:
    # https://github.com/Homebrew/legacy-homebrew/issues/40585
    - qpaintengine_mac.patch  # [osx]
    # Make Qt work with Ubuntu modifications to scrollbars for Gtk
    - ubuntu_disable_scrollbars.patch  # [linux]
    # Build QtWebkit with gcc-6, on platform linux-g++
    - qtwebkit-gcc-6.patch  # [linux]
    # Disable warning about Windows 10 not being a supported platform by Qt
    - disable_win10_warning.patch  # [win]
    # On Windows, for VS 2015 (Python 3.5+), rather drastic modifications are
    # necessary because Microsoft finally got around to defining some standard
    # functions. There's the vs_2015_int.patch file that does this. The changes in this patch were
    # found in forums, and originated at (Author appears to be Peter Zhigalov):
    # https://fami.codefreak.ru/gitlab/peter/qt4/commit/45e8f4eef3923e03c6939d0c17170980685857ef.diff
    - vs2015_int_fix.patch  # [win and py >= 35]
    - gcc-7.patch
    - clang.patch  # [osx]
    - clang-cxx11.patch  # [osx]
    - qmake-osxapp-fix.patch  # straight-up bug!
    - qt4-openssl-1.1.patch

build:
  number: 8
  skip: true  # [win and py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]
  script_env:
    - NJOBS
  run_exports:
    - {{ pin_subpackage('qt4', max_pin='x.x') }}

requirements:
  build:
    - jom  # [win]
    - python
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    - {{ compiler('cxx') }}
  host:
    - dbus-cxx 0.9.*
    - fontconfig {{ fontconfig }}  # [linux]
    - freeglut  # [linux]
    - freetype {{ freetype }}  # [linux]
    - icu {{ icu }}
    - jpeg {{ jpeg }}
    - libpng {{ libpng }}
    - libtiff {{ libtiff }}
    - libuuid {{ libuuid }}  # [linux]
    - libxml2 {{ libxml2 }}
    - openssl {{ openssl }}
    - pango {{ pango }}  # [linux]
    - xorg-libx11
    - xorg-libxext
    - xorg-xextproto
    - xorg-xproto
    - zlib {{ zlib }}
  run:
    # these deps don't auto-add themselves (yet?)
    - dbus-cxx 0.9.*
    - freeglut  # [linux]
    - icu {{ icu }}
    - pango {{ pango }}  # [linux]
    - xorg-libx11
    - xorg-libxext

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - test

about:
    home: http://qt-project.org
    license: LGPL
    license_file: LICENSE.LGPL
    summary: 'Version 4 of Qt, a cross-platform application and UI framework.'
    doc_url: http://doc.qt.io/
    dev_url: https://github.com/qtproject

extra:
  recipe-maintainers:
    - pkgw
