# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `cmake-fixes.patch`.
# Build on CentOS 5.

package:
  name: casa-asap
  version: "4.5.2"

source:
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_5/
  svn_rev: 36115
  svn_ignore_externals: yes
  patches:
    - cmake-fixes.patch
    - wcslib-version.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - boost 1.57.0 # version fix is temp hack for unavailable ICU 56
    - casa-nrao-casacore
    - casa-tools
    - cfitsio
    - cmake
    - libgfortran 3.0 #[linux]
    - libxml2
    - nomkl
    - numpy
    - openblas #[not osx]
    - pgplot
    - python
    - rpfits
    - wcslib
  run:
    - boost 1.57.0 # version fix is temp hack for unavailable ICU 56
    - casa-nrao-casacore
    - casa-tools
    - cfitsio
    - libgfortran 3.0 #[linux]
    - libxml2
    - numpy
    - openblas #[not osx]
    - pgplot
    - python
    - wcslib

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: single-dish radio telescope analysis package for CASA
