# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: eigen
  version: "3.2.4"

source:
  fn: 3.2.4.tar.bz2
  url: http://bitbucket.org/eigen/eigen/get/3.2.4.tar.bz2
  md5: 4c4b5ed9a388a1e475166d575af25477

build:
  number: 0

requirements:
  build:
    - cmake

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  summary: C++ template library for matrix computations

  
