# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: libsakura
  version: "1.1.1"

source:
  fn: libsakura-1.1.1.tar.gz
  url: https://svn.cv.nrao.edu/casa/devel/libsakura-1.1.1.tar.gz
  md5: 54d6b4364f1765ee3284fe2a58c93619
  patches:
    - compile-fixes.patch

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - eigen
    - fftw

about:
  home: http://alma.mtk.nao.ac.jp/j/
  license: GPL version 3
  summary: C++ library for fast image manipulations
