# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# This single package includes a fairly complete X11 stack. This is needed
# because Gtk+ 3 requires XInput version 2, which is not availabe on
# RHEL/CentOS 5, and (shockingly) there are machines out there still stuck
# on that ancient OS.

# HACK: the current (8.5.18-0) version of `tk` on OS X includes some random
# X11 headers. To build we need Python which means we need tk, so tk's headers
# take precedence when the package is generated -- so, for instance, our
# package cannot contain include/X11/Xlib.h. We use a post-link script to work
# around this in horrible fashion. See
# https://github.com/ContinuumIO/anaconda-issues/issues/600 .

package:
  name: modern-xorg-stack
  version: "2016.03"

source:
  fn: modern-xorg-stack-2016.03.tar.bz2
  url: http://newton.cx/~peter/files/modern-xorg-stack-2016.03.tar.bz2
  sha1: 85e6d671567956f235b4805c60e6e7cd9d1f616b
  patches:
    - no-lib64.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - python

about:
  home: http://www.x.org/
  license: X.org license
  summary: modern versions of the X11 client libraries
