# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# This single package includes a fairly complete X11 stack. This is needed
# because Gtk+ 3 requires XInput version 2, which is not availabe on
# RHEL/CentOS 5, and (shockingly) there are machines out there still stuck
# on that ancient OS.

package:
  name: modern-xorg-stack
  version: "2015.12"

source:
  fn: modern-xorg-stack-2015.12.tar.bz2
  url: http://newton.cx/~peter/files/modern-xorg-stack-2015.12.tar.bz2
  sha1: 6841e523ee2d203ac6dacef25ef0fafbcd9af06c

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python

about:
  home: http://www.x.org/
  license: X.org license
  summary: modern versions of the X11 client libraries
