# Copyright 2017-2022 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "wsclean" %}
{% set version = "3.1" %}
{% set compat_version = "3.1" %}
{% set download_id = "33647495" %}
{% set sha256 = "ecc58bdff1aa428c17c9915e6d8fddd5aa397cb5f0848f224f3e7932aa15fce0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/aroffringa/{{ name }}/-/package_files/{{ download_id }}/download
  fn: wsclean-{{ download_id }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - osx.patch  # [osx]

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - boost-cpp {{ boost_cpp }}
    - casacore * nompi_*
    - fftw {{ fftw }}
    - gsl {{ gsl }}
  run:
    - {{ pin_compatible('boost-cpp') }}

test:
  commands:
    - OPENBLAS_NUM_THREADS=1 wsclean -version

about:
  home: https://gitlab.com/aroffringa/wsclean
  license: GPLv3
  summary: fast, widefield interferometric imaging
