# Copyright 2017-2021 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "wsclean" %}
{% set version = "2.10.1" %}
{% set compat_version = "2.10" %}
{% set sha256 = "778edc1e73ce346a62063eef570054c268727a0fab47b999549d678a8b26ee1e" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ compat_version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - osx.patch  # [osx]

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - boost-cpp {{ boost }}
    - casacore 3.3.*  # NB: casa-tools currently requires casacore 3.3 and we need to stay compatible
    - fftw {{ fftw }}
    - gsl {{ gsl }}
  run:
    - {{ pin_compatible('boost-cpp') }}

test:
  commands:
    - wsclean -version

about:
  home: http://wsclean.sourceforge.net/
  license: GPLv3
  summary: fast, widefield interferometric imaging
