# Copyright 2017-2018 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "wsclean" %}
{% set version = "2.6" %}
{% set sha256 = "5352805f6c156a59f1274b33e574ec7fdfb868c932038378ec19a8fa3cd73abf" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - osx.patch  # [osx]

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - boost
    - casacore 2.4.*
    - fftw 3.3.*
    - gsl

test:
  commands:
    - wsclean -version

about:
  home: http://wsclean.sourceforge.net/
  license: GPLv3
  summary: fast, widefield interferometric imaging
