# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: pygobject3
  version: 3.12.0

source:
  fn: pygobject-3.12.0.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.12/pygobject-3.12.0.tar.xz
  md5: f62700cdd7919b5afbc1de54569df648
  patches:
    - typelib-path.patch

build:
  number: 1

requirements:
  build:
    - cairo-gobject
    - glib
    - gobject-introspection
    - libffi
    - py2cairo
    - python
  run:
    - cairo-gobject
    - glib
    - gobject-introspection
    - libffi
    - py2cairo
    - python

about:
  home: http://www.gtk.org/
  license: LGPL
