# Copyright 2015-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# The data files are now tracked in a repo that's managed with Git LFS. The
# best way that I've come up with to make a tractable build is to do the
# checking out manually; I found some random empty tar file on a CDN that we
# can use as the "source" to make 'conda-build' happy.

package:
  name: casa-data
  version: r20200806

source:
  fn: empty-test-tarball-1.0.2.tgz
  url: https://registry.npmjs.org/empty-test-tarball/-/empty-test-tarball-1.0.2.tgz
  sha256: f0132c1a34408eae6353f01145220450aa8cbaaccfd99223479ef43133ea4eaf

build:
  noarch: generic
  number: 0

requirements:
  build:
    - git
    - git-lfs

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: supporting data files for CASA
