# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: casa-asap
  version: "4.4"

source:
  # Due to ASAP's dumb build system, we have to check out the whole release
  # tree.
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_4/
  svn_rev: 33623
  svn_ignore_externals: yes
  patches:
    - cmake-fixes.patch

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - atlas
    - boost
    - casa-nrao-casacore
    - casa-tools
    - cfitsio
    - cmake
    - libxml2
    - pgplot
    - rpfits
    - wcslib
  run:
    - boost
    - casa-nrao-casacore
    - casa-tools
    - cfitsio
    - libxml2
    - pgplot
    - wcslib

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: single-dish radio telescope analsysis package for CASA
