# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: dbus-client
  version: "1.8.16"

source:
  fn: dbus-1.8.16.tar.gz
  url: http://dbus.freedesktop.org/releases/dbus/dbus-1.8.16.tar.gz
  md5: 020824a38850501e7d6ba8307a7c5ac3
  patches:
    - skip-extras.patch

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python

about:
  home: http://dbus.freedesktop.org/
  license: LGPL
