# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: qwt5
  version: "5.2.3"

source:
  fn: qwt-5.2.3.tar.bz2
  url: http://sourceforge.net/projects/qwt/files/qwt/5.2.3/qwt-5.2.3.tar.bz2/download
  md5: 7d37a11d02bc7d095d0ca6427ec97b8d

build:
  number: 2
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - qt4 4.8.*
  run:
    - qt4 4.8.*

about:
  home: http://qwt.sourceforge.net/
  license: Qwt License version 1.0
  summary: version 5 of a technical widget library for Qt
