# Copyright Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "rubbl-rxpackage" %}
{% set version = "0.1.8" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/pkgw/{{ name }}/archive/{{ name }}@{{ version }}.tar.gz
  sha256: 99b921476b8f020df30ee1061541ec57c431e26b8c5d818163bcfa3d0dc9f450

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}

test:
  commands:
    - rubbl-rxpackage flagts --help
    - rubbl-rxpackage peel --help
    - rubbl-rxpackage spwglue --help

about:
  home: https://github.com/pkgw/rubbl-rxpackage
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Radio astronomy reduction utilities written in Rust, using the Rubbl framework'
  dev_url: https://github.com/pkgw/rubbl-rxpackage

extra:
  recipe-maintainers:
    - pkgw
