# Copyright Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# NB: we're not providing `rfigui`.

{% set version = "2.15.0" %}

package:
  name: aoflagger
  version: {{ version }}

source:
  url: https://gitlab.com/aroffringa/aoflagger/-/archive/v{{ version }}/aoflagger-v{{ version }}.tar.gz
  sha256: 0d080471944fd968403b69946ccf5076d7cd9c11a4aa626bb10dc926bdd4828e
  patches:
    - boost-python3.patch
    - cxxflags.patch
    - compile-fixes.patch

build:
  number: 3

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake <4
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - ninja
    - pkg-config
    - python
  host:
    - casacore
    - cfitsio 4.6.2  # force migration pin for correct casacore
    - fftw
    - gsl
    - hdf5
    - libblas
    - libboost-devel 1.86  # force migration pin for correct casacore
    - libboost-python 1.86  # force migration pin for correct casacore
    - libcblas
    - libcurl  # overlinky dep
    - liblapack
    - libpng
    - libxml2
    - lua
    - numpy 2  # force migration pin for correct casacore
    - python
    - zlib  # overlinky dep
  run:
    - {{ pin_compatible("libboost-python") }}
    - mkl  # shouldn't need to specify this explicitly
    - {{ pin_compatible("numpy") }}
    - python

about:
  home: http://aoflagger.sourceforge.net/
  license: GPLv3
  summary: automatic flagging of interference in radio astronomical data sets
