# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `so-versioning.patch`.

package:
  name: casa-nrao-casacore
  version: "4.6.0"

source:
  # FIXME: this server currently (2015/12) has a bad SSL certificate, breaking
  # the checkout! It can be worked around if you manually approve the cert.
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_6/
  svn_rev: 36590
  svn_ignore_externals: yes
  patches:
    - so-versioning.patch
    - default-root.patch
    - ncursesw.patch

build:
  number: 2
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - boost 1.57.0 # fixed version is hack for icu issue seen in casa-tools
    - cfitsio
    - cmake
    - fftw
    - hdf5 >=1.8.15.1
    # - libgfortran 3.0.0 #[linux] XXX: causes spurious-seeming dep conflict error
    - ncurses 5.9
    - nomkl # speeds up by avoiding big download
    - numpy
    - openblas #[not osx]
    - python >=2.7,<3
    - readline
    - wcslib
  run:
    - boost 1.57.0 # fixed version is hack for icu issue seen in casa-tools
    - cfitsio
    - fftw
    - hdf5 >=1.8.15.1
    - libgfortran 3.0.0 #[linux]
    - ncurses 5.9
    - numpy
    - openblas #[not osx]
    - python >=2.7,<3
    - readline
    - wcslib

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: core libraries for CASA
