# Copyright 2015-2021 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# A new tag must be pushed to GitHub for every update!

{% set name = "casa-tools" %}
{% set version = "5.6.3" %}
{% set build = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/pkgw/casa.git
  git_rev: casa3k-{{ version }}_{{ build }}

build:
  number: {{ build }}
  skip: true  # [win]
  script_env:
    - NJOBS
  run_exports:
    - {{ pin_subpackage('casa-tools', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - boost {{ boost }}
    - boost-cpp {{ boost_cpp }}
    - casacore 3.3.*  # doesn't (currently) compile against casacore 3.4
    - cfitsio {{ cfitsio }}
    - dbus-cxx 0.9.*
    - dbus {{ dbus }}
    - fftw
    - gsl {{ gsl }}
    - libblas {{ libblas }}
    - libcblas {{ libcblas }}
    - liblapack {{ liblapack }}
    - libsakura 3.0.*
    - libxml2 {{ libxml2 }}
    - libxslt
    - ncurses {{ ncurses }}
    - pgplot 5.2.*
    - readline {{ readline }}
    - rpfits 2.*
    - qt4 4.8.*
    - qwt5 5.2.*
    - xerces-c28
  run:
    # Packages that don't (yet) auto-add their runtime deps
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('boost-cpp') }}
    - libsakura 3.0.*
    - pgplot 5.2.*
    - rpfits 2.*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://casa.nrao.edu/
  license: GPLv2
  summary: scientific tool implementations for CASA

extra:
  recipe-maintainers:
    - pkgw
